# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
author: Andreas Ziegler # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Andreas Ziegler # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/Andreas-Ziegler-219684904733574/
    - https://ch.linkedin.com/in/andreas-ziegler-34087467
    - https://github.com/AndreasAZiegler
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Meine Gedanken und Ideen" # The post list page content
    feature_text: |
      Wilkommen auf meinem Blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: de-CH # Set the site language
title: "Andreas Ziegler" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/android-chrome-192x192.png" # Site logo, also used in jekyll-seo-tag
description: "Andreas Ziegler politisiert für die Junge EVP." # Site description and default description, also used in jekyll-seo-tag
url: "https://aaziegler.ch" # Site url, also used in jekyll-seo-tag
baseurl: ""
email: "info@aaziegler.ch"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/favicon-16x16.png'
  32: '/assets/logos/favicon-32x32.png'
  96: '/assets/logos/favicon-96x96.png'
  192: '/assets/logos/android-chrome-192x192.png'

# 9. Site navigation
navigation_header:
  Klimapolitik: /klima/
  Bildungspolitik: /bildung/
  Wirtschaftspolitik: /wirtschaft/
  Blog: /blog/

navigation_footer:
  Created by Andreas Ziegler: https://www.aaziegler.ch

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://ch.linkedin.com/in/andreas-ziegler-34087467
  GitHub: https://github.com/AndreasAZiegler
  link: https://www.aaziegler.ch

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  facebook: "#3B5998"
  # Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
